CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(260) NOT NULL,
    email VARCHAR(260) NOT NULL UNIQUE,
    phone VARCHAR(255),
    role VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
