version: "3.8"

services:
  db-users:
    image: postgres:latest
    container_name: db-users
    ports:
      - "5433:5432"
    networks:
      - bookstore-network
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123456
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d users"]
      interval: 30s
      timeout: 10s
      retries: 5

  db-library:
    image: postgres:latest
    container_name: db-library
    ports:
      - "5434:5432"
    networks:
      - bookstore-network
    environment:
      - POSTGRES_DB=libraries
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123456
    volumes:
      - postgres_library_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d libraries"]
      interval: 30s
      timeout: 10s
      retries: 5

  db-monitoring:
    image: postgres:latest
    container_name: db-monitoring
    ports:
      - "5435:5432"
    networks:
      - bookstore-network
    environment:
      - POSTGRES_DB=monitoring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123456
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d users"]
      interval: 30s
      timeout: 10s
      retries: 5    

  eurekaserver:
    build:
      context: ./system.eurekaserver
    ports:
      - "8761:8761"
    networks:
      - bookstore-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_INSTANCE_HOSTNAME=eurekaserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  gateway:
    build:
      context: ./system.gateway
    ports:
      - "8080:8080"
    depends_on:
      eurekaserver:
        condition: service_healthy
    networks:
      - bookstore-network
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=gateway
    restart: on-failure

  userservice:
    build:
      context: ./userservice
    ports:
      - "8081:8081"
    depends_on:
      eurekaserver:
        condition: service_healthy
      db-users:
        condition: service_healthy
    networks:
      - bookstore-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-users:5432/users?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin123456
      - JWT_SECRET=user@admin
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=userservice
      - SPRING_APPLICATION_NAME=userservice
    restart: on-failure

  libraryservice:
    build:
      context: ./libraryservice
    ports:
      - "8082:8082"
    depends_on:
      eurekaserver:
        condition: service_healthy
      db-library:
        condition: service_healthy
    networks:
      - bookstore-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-library:5432/libraries?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin123456
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=libraryservice
      - SPRING_APPLICATION_NAME=libraryservice
    restart: on-failure

networks:
  bookstore-network:
    driver: bridge

volumes:
  postgres_users_data:
  postgres_library_data:
