spring:
  application:
    name: libraryservice

  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    sql:
      init:
        platform: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/libraries?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
    username: postgres
    password: admin123456


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  servlet:
    context-path: /api/library
  port: 8082