spring:
  application:
    name: userservice

  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    sql:
      init:
        platform: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/users?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
    username: postgres
    password: admin123456


api:
  security:
    token:
      secret: user@adm

server:
  servlet:
    context-path: /api
  port: 8081