spring:
  application:
    name: userservice

  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    sql:
      init:
        platform: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/users?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123456}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health, metrics'
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
      show-details: always


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

api:
  security:
    token:
      secret: ${JWT_SECRET:user@admin}

server:
  servlet:
    context-path: /api/userservice
  port: 8081
